from cod_analytics.classes import RemapClass


class MapRemap(RemapClass):
    mp_deadzone = "Arklov Peak"
    mp_aniyah_tac = "Aniyah Incursion"
    mp_hackney_am = "Hackney Yard"
    mp_backlot2 = "Talsik Backlot"
    mp_runner = "Gun Runner"
    mp_scrapyard = "Scrapyard"
    mp_cave_am = "Azhir Cave"
    mp_crash2 = "Crash"
    mp_oilrig = "Petrov Oil Rig"
    mp_hardhat = "Hardhat"
    mp_garden = "Cheshire Park"
    mp_rust = "Rust"
    mp_spear = "Rammaza"
    mp_hideout = "Khandor Hideout"
    mp_petrograd = "St. Petrograd"
    mp_shipment = "Shipment"
    mp_killhouse = "Killhouse"
    mp_m_speed = "Shoothouse"
    mp_harbor = "Suldal Harbor"
    mp_emporium = "Atlas Superstore"
    mp_vacant = "Vacant"
    mp_village2 = "Hovec Sawmill"
    mp_broadcast2 = "Broadcast"
    mp_piccadilly = "Picadilly"
    mp_malyshev = "Tank Factory"


class MapPathRemap(RemapClass):
    mp_deadzone = "ArklovPeak.png"
    mp_aniyah_tac = "AniyahIncursion.png"
    mp_hackney_am = "HackneyYard.png"
    mp_backlot2 = "TalsikBacklot.png"
    mp_runner = "GunRunner.png"
    mp_scrapyard = "Scrapyard.png"
    mp_cave_am = "AzhirCave.png"
    mp_crash2 = "Crash.png"
    mp_oilrig = "PetrovOilRig.png"
    mp_hardhat = "Hardhat.png"
    mp_garden = "CheshirePark.png"
    mp_rust = "Rust.png"
    mp_spear = "Rammaza.png"
    mp_hideout = "KhandorHideout.png"
    mp_petrograd = "StPetrograd.png"
    mp_shipment = "Shipment.png"
    mp_killhouse = "Killhouse.png"
    mp_m_speed = "Shoothouse.png"
    mp_harbor = "SuldalHarbor.png"
    mp_emporium = "AtlasSuperstore.png"
    mp_vacant = "Vacant.png"
    mp_village2 = "HovecSawmill.png"
    mp_broadcast2 = "Broadcast.png"
    mp_piccadilly = "Picadilly.png"
    mp_malyshev = "TankFactory.png"


class MapRemapSimple(RemapClass):
    arklov = "mp_deadzone"
    aniyah = "mp_aniyah_tac"
    hackney = "mp_hackney_am"
    backlot = "mp_backlot2"
    gun_runner = "mp_runner"
    scrapyard = "mp_scrapyard"
    cave = "mp_cave_am"
    crash = "mp_crash2"
    oilrig = "mp_oilrig"
    hardhat = "mp_hardhat"
    cheshire_park = "mp_garden"
    rust = "mp_rust"
    rammaza = "mp_rust"
    khandor = "mp_hideout"
    petrograd = "mp_petrograd"
    shipment = "mp_shipment"
    killhouse = "mp_killhouse"
    shoothouse = "mp_m_speed"
    harbor = "mp_harbor"
    superstore = "mp_emporium"
    vacant = "mp_vacant"
    sawmill = "mp_village2"
    broadcast = "mp_broadcast2"
    piccadilly = "mp_piccadilly"
    tank_factory = "mp_malyshev"
